import * as stylex from '@stylexjs/stylex'
import { tokens } from './tokens.stylex'

/**
 * Recipes shared by more than one editor surface: page chrome, sketchy controls,
 * form fields and inline hints. Component-local layout lives next to its component.
 */
export const ui = stylex.create({
  body: {
    margin: 0,
    color: tokens.ink,
    backgroundColor: tokens.paper,
    fontFamily: tokens.handFont,
    fontSize: 19,
    lineHeight: 1.85,
    letterSpacing: '0.02em',
    '::selection': {
      backgroundColor: tokens.accentSoft,
    },
    '@media (max-width: 700px)': {
      fontSize: 18,
    },
  },
  eyebrow: {
    fontSize: 14,
    letterSpacing: 2,
    color: tokens.accentText,
  },
  pageTitle: {
    fontSize: 34,
    lineHeight: 1.3,
    letterSpacing: 0,
    margin: '12px 0 24px',
    fontWeight: 400,
    textDecorationLine: 'underline',
    textDecorationStyle: 'wavy',
    textDecorationColor: tokens.accentSoft,
    textDecorationThickness: 5,
    textUnderlineOffset: 9,
    '@media (max-width: 700px)': {
      fontSize: 28,
    },
  },
  section: {
    paddingBlock: 22,
    borderTopWidth: 2,
    borderTopStyle: 'dashed',
    borderTopColor: tokens.ink,
  },
  sectionFirst: {
    borderTopWidth: 0,
    borderTopStyle: 'none',
  },
  sectionHeading: {
    display: 'flex',
    gap: 12,
    alignItems: 'center',
    fontSize: 20,
    fontWeight: 400,
    margin: '0 0 14px',
  },
  sectionNumber: {
    display: 'inline-grid',
    placeItems: 'center',
    flexShrink: 0,
    width: 38,
    height: 38,
    fontSize: 14,
    color: tokens.ink,
    backgroundColor: tokens.accentSoft,
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: tokens.ink,
    borderRadius: '50%',
    transform: 'rotate(-4deg)',
  },
  aside: {
    paddingBlock: 30,
    paddingInline: 28,
    backgroundColor: tokens.card,
    borderRightWidth: 2,
    borderRightStyle: 'solid',
    borderRightColor: tokens.ink,
  },
  asideCompact: {
    '@media (max-width: 1000px)': {
      paddingBlock: 24,
      paddingInline: 20,
    },
    '@media (max-width: 700px)': {
      paddingBlock: 24,
      paddingInline: 20,
      borderRightWidth: 0,
      borderRightStyle: 'none',
      borderTopWidth: 2,
      borderTopStyle: 'solid',
      borderTopColor: tokens.ink,
    },
  },
  asideCentered: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'start',
    paddingBlock: 30,
    paddingInline: 28,
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: tokens.ink,
    borderRadius: tokens.sketchCard,
    boxShadow: tokens.shadowLg,
  },
  label: {
    display: 'block',
    fontSize: 16,
    lineHeight: 1.6,
  },
  field: {
    display: 'block',
    width: '100%',
    marginTop: 8,
    outlineOffset: 3,
    paddingBlock: 9,
    paddingInline: 13,
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: tokens.ink,
    borderRadius: tokens.sketchAlt,
    backgroundColor: 'white',
    color: tokens.ink,
    boxShadow: tokens.shadowField,
    fontFamily: 'inherit',
    fontSize: 'inherit',
    lineHeight: 1.5,
    ':focus-visible': {
      outlineWidth: 3,
      outlineStyle: 'dashed',
      outlineColor: tokens.accent,
      outlineOffset: 3,
    },
  },
  /** Mirrors the mirrored sketch radius the label parity picks for even fields. */
  fieldAlt: {
    borderRadius: tokens.sketch,
  },
  textarea: {
    resize: 'vertical',
    minHeight: 64,
  },
  select: {
    cursor: 'pointer',
  },
  fileField: {
    fontSize: 14,
    paddingBlock: 10,
    paddingInline: 8,
    maxWidth: '100%',
    lineHeight: 1.5,
    '::file-selector-button': {
      marginRight: 10,
      paddingBlock: 6,
      paddingInline: 12,
      fontFamily: 'inherit',
      fontSize: 13,
      textTransform: 'uppercase',
      letterSpacing: '0.04em',
      backgroundColor: tokens.accentSoft,
      color: tokens.accentText,
      borderWidth: 2,
      borderStyle: 'solid',
      borderColor: tokens.ink,
      borderRadius: tokens.sketch,
      boxShadow: tokens.shadowField,
    },
  },
  checkbox: {
    width: 20,
    height: 20,
    accentColor: tokens.accent,
    outlineOffset: 3,
    color: 'inherit',
    fontFamily: 'inherit',
    fontSize: 'inherit',
    lineHeight: 'inherit',
    ':focus-visible': {
      outlineWidth: 3,
      outlineStyle: 'dashed',
      outlineColor: tokens.accent,
      outlineOffset: 3,
      borderRadius: 6,
    },
  },
  details: {
    fontSize: 16,
  },
  summary: {
    paddingBlock: 10,
    color: tokens.accentText,
    cursor: 'pointer',
    outlineOffset: 0,
    textDecorationLine: 'underline',
    textDecorationStyle: 'wavy',
    textDecorationColor: tokens.accentSoft,
    textDecorationThickness: 3,
    textUnderlineOffset: 5,
    ':focus-visible': {
      outlineWidth: 3,
      outlineStyle: 'dashed',
      outlineColor: tokens.accent,
      borderRadius: 6,
    },
  },
  detailsLabel: {
    margin: '12px 0',
  },
  hint: {
    fontSize: 15,
    lineHeight: 1.7,
    color: tokens.inkMuted,
    margin: '10px 0',
  },
  fileMeta: {
    fontSize: 15,
    lineHeight: 1.7,
    color: tokens.inkMuted,
    margin: '10px 0',
    overflowWrap: 'anywhere',
  },
  status: {
    fontSize: 15,
    color: tokens.inkMuted,
    marginTop: 10,
  },
  error: {
    fontSize: 16,
    color: tokens.danger,
    backgroundColor: tokens.dangerSoft,
    paddingBlock: 12,
    paddingInline: 16,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: tokens.danger,
    borderRadius: tokens.sketchCard,
    overflowWrap: 'anywhere',
  },
  errorButton: {
    display: 'block',
    marginTop: 10,
    backgroundColor: 'white',
    ':hover': {
      backgroundColor: 'white',
    },
  },
  button: {
    paddingBlock: 8,
    paddingInline: 16,
    outlineOffset: 3,
    color: tokens.ink,
    backgroundColor: tokens.accentSoft,
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: tokens.ink,
    borderRadius: tokens.sketch,
    boxShadow: tokens.shadow,
    fontFamily: 'inherit',
    fontSize: 15,
    lineHeight: 1.6,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
    transform: 'rotate(-0.3deg)',
    cursor: 'pointer',
    transitionProperty: 'transform, box-shadow, background-color',
    transitionDuration: '0.12s',
    transitionTimingFunction: 'ease',
    ':hover:not(:disabled)': {
      backgroundColor: tokens.accentSoftest,
    },
    ':active': {
      transform: 'translate(2px, 3px)',
      boxShadow: `0 0 0 ${tokens.ink}`,
    },
    ':disabled': {
      opacity: 0.45,
      cursor: 'not-allowed',
      boxShadow: 'none',
      transform: 'none',
    },
    ':focus-visible': {
      outlineWidth: 3,
      outlineStyle: 'dashed',
      outlineColor: tokens.accent,
      outlineOffset: 3,
    },
  },
  /** Second-of-type sketchy controls lean the other way, like the drawn buttons. */
  buttonAlt: {
    borderRadius: tokens.sketchAlt,
    transform: 'rotate(0.35deg)',
    ':disabled': {
      transform: 'rotate(0.35deg)',
    },
  },
  textButton: {
    paddingBlock: 10,
    paddingInline: 4,
    color: 'inherit',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderStyle: 'none',
    borderRadius: 4,
    boxShadow: `0 -8px ${tokens.accentSoft} inset`,
    fontFamily: 'inherit',
    fontSize: 16,
    letterSpacing: 0,
    textTransform: 'none',
    textDecoration: 'none',
    transform: 'none',
    ':hover:not(:disabled)': {
      backgroundColor: 'transparent',
      boxShadow: `0 -12px ${tokens.accentSoft} inset`,
    },
  },
  primary: {
    display: 'inline-block',
    paddingBlock: 12,
    paddingInline: 20,
    outlineOffset: 3,
    color: '#fff',
    backgroundColor: tokens.ink,
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: tokens.ink,
    borderRadius: tokens.sketchAlt,
    boxShadow: '3px 4px 0 rgba(16, 18, 17, 0.3)',
    fontFamily: 'inherit',
    fontSize: 16,
    letterSpacing: '0.06em',
    textAlign: 'center',
    textDecoration: 'none',
    transform: 'rotate(0.25deg)',
    cursor: 'pointer',
    transitionProperty: 'transform, box-shadow, background-color',
    transitionDuration: '0.12s',
    transitionTimingFunction: 'ease',
    // Compound pseudo keeps its priority above the base button hover, like the
    // original `.primary:hover` rule did.
    ':hover:not(:disabled)': {
      color: '#fff',
      backgroundColor: '#000',
    },
    ':disabled': {
      backgroundColor: '#8a938e',
      borderColor: '#8a938e',
      boxShadow: 'none',
    },
    ':focus-visible': {
      outlineWidth: 3,
      outlineStyle: 'dashed',
      outlineColor: tokens.accent,
      outlineOffset: 3,
    },
  },
  /** Step-navigation primaries carry a vermilion cast shadow instead of the ink one. */
  primaryShadow: {
    boxShadow: '3px 4px 0 rgba(255, 50, 30, 0.55)',
  },
  primaryStretch: {
    flex: 1,
  },
  primaryFill: {
    width: '100%',
  },
  /** Letter/icon choice cards used by the mask picker and the icon gallery. */
  fontCard: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
    paddingBlock: 10,
    paddingInline: 4,
    lineHeight: 1.2,
    ':disabled': {
      opacity: 0.55,
    },
  },
  fontCardSelected: {
    backgroundColor: tokens.accentSoft,
    borderWidth: 3,
    ':hover:not(:disabled)': {
      backgroundColor: tokens.accentSoft,
    },
  },
  fontGlyph: {
    display: 'grid',
    placeItems: 'center',
    fontSize: 34,
    lineHeight: 1.25,
    minHeight: 44,
  },
  fontName: {
    fontSize: 11,
    lineHeight: 1.4,
    letterSpacing: 0,
    textAlign: 'center',
    textTransform: 'none',
  },
  /** Highlighter-pen treatment shared by artifact and inline links. */
  textLink: {
    color: 'inherit',
    paddingInline: 4,
    outlineOffset: 3,
    textDecoration: 'none',
    boxShadow: `0 -8px ${tokens.accentSoft} inset`,
    ':hover': {
      boxShadow: `0 -14px ${tokens.accentSoft} inset`,
    },
    ':focus-visible': {
      outlineWidth: 3,
      outlineStyle: 'dashed',
      outlineColor: tokens.accent,
      outlineOffset: 3,
      borderRadius: 6,
    },
  },
})
